[env:tac1100_esp8266]
platform = espressif8266
board = d1_mini            ; 4 MB flash; dla gołego ESP-12 też może być esp12e
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
    https://github.com/SUPLA/supla-device.git
    4-20ma/ModbusMaster@^2.0.1
